In [2]:
import numpy as np
import pandas as pd

In [3]:
Education = pd.read_csv('UNHCR-KEN-2018-SEA-Kalobeyei-Education.csv')
Energy = pd.read_csv('UNHCR-KEN-2018-SEA-Kalobeyei-Energy.csv')
Food = pd.read_csv('UNHCR-KEN-2018-SEA-Kalobeyei-Food.csv')
Household = pd.read_csv('UNHCR-KEN-2018-SEA-Kalobeyei-Household.csv')
Member = pd.read_csv('UNHCR-KEN-2018-SEA-Kalobeyei-Member.csv')
Nonfood = pd.read_csv('UNHCR-KEN-2018-SEA-Kalobeyei-Nonfood.csv')

In [9]:
#Food Rename
Food.rename(columns={"s12q1":"hh_purchasedfood7d", "s12q2":"amountfood_purchased7d", 
                     "s12q4":"foodspent_localcurrecny", "s12q6": "foodconsumed7d",
                     "s12q2_a": "daystoeatfood","s12q7": "foodwasfree", 
                     "cons_q_kg": "quantityfood_consumedkg", 
                     "cons_q_kg_pc": "quantityfood_consumedkg_pc"})

,hhid,s1q2,hhsize,hhmod,mod_opt,item_id,item_name,hh_purchasedfood7d,amountfood_purchased7d,daystoeatfood,...,purc_uv,national_uv_2015_16,purc_uv_med_2018_19,cons_conv2kg,quantityfood_consumedkg,quantityfood_consumedkg_pc,fcons_value,fcons_value_capita,weight,popweight
0,10,Village 1,5,1,core,111,FORTIFIED MAIZE FLOUR,Yes,24.0,Kgs,...,70.83,55.00000,64.16376,1.000,2.00,0.400000,128.327500,25.665510,5.557168,27.78584
1,10,Village 1,5,1,core,101,AROMATIC UNBROKEN RICE (PISHORI/BASMATI E.T.C),Yes,11.0,Kgs,...,104.55,120.00000,139.99370,1.000,1.00,0.200000,139.993700,27.998730,5.557168,27.78584
2,10,Village 1,5,1,core,702,ONION - BULBS,Yes,2.0,Kgs,...,120.00,100.00000,116.66140,0.280,1.96,0.392000,228.656300,45.731270,5.557168,27.78584
3,10,Village 1,5,1,option 1,1012,BAKING POWDER /BICARBONATE,Yes,400.0,Grams,...,500.00,250.00000,291.65350,0.001,0.01,0.002000,2.916535,0.583307,5.557168,27.78584
4,10,Village 1,5,1,core,703,CABBAGES,Yes,1.0,Heap,...,200.00,22.22222,25.92476,0.500,0.50,0.100000,12.962380,2.592475,5.557168,27.78584
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18104,6004,Village 3,12,1,core,901,SUGAR CANE,Yes,1.0,Pcs,...,166.67,13.88889,16.20297,NaN,NaN,NaN,0.000000,0.000000,5.557168,66.68602
18105,6004,Village 3,12,1,core,705,TOMATOES,Yes,2.0,Pcs,...,33.33,70.00000,81.66297,NaN,NaN,NaN,0.000000,0.000000,5.557168,66.68602
18106,6004,Village 3,12,1,core,702,ONION - BULBS,Yes,1.0,Kgs,...,120.00,100.00000,116.66140,1.000,1.00,0.083333,116.661400,9.721783,5.557168,66.68602
18107,6004,Village 3,12,1,core,1702,TRADITIONAL BEER,Yes,1.0,Cup,...,20.00,50.00000,58.33070,2.000,2.00,0.166667,116.661400,9.721783,5.557168,66.68602
18108,6004,Village 3,12,1,core,114,WHEAT FLOUR-WHITE,Yes,24.0,Kgs,...,77.08,70.00000,81.66297,1.000,2.00,0.166667,163.325900,13.610500,5.557168,66.68602

In [ ]:
#Household Rename 
Household.rename(columns={"s6q1": "number_dwellings", "s6q2": "number_habitablerooms", 
                          "s6q3":"floor_material", "s6q4":"roof_material", "s6q5":"wall_material"
                          "s6q6":"drikingwater_source", "s6q7": "drinkingwater_insufficientquanities", 
                          "s6q8": "toilet_type", "s6q9": "share_toilet", "s6q11": "lighting_source"
                          "s6q13": "payrent_dwelling", "s6q14": "rentpaid_shillings", "s7q1": "own_radio",
                          "s7q2": "own_television", "s7q3": "own_satelitedish", "s7q4": "own_smartphone",
                          "s7q5":"own_refrigerator", "s7q6": "own_table", "s7q7": "own_bed", "s7q8": "own_mattress", 
                          "s7q9":"own_mosquitonet", "s7q10":"own_fan", "s7q11": "own_bicycle", "s7q12":"own_motorcycle", 
                          "s7q13": "own_car", "s7q14": "own_generator", "s7q15": "own_solarpanels", "s7q16": "own_kerosenestove",
                          "s7q17": "own_charcoaljiko", "s7q18": "own_wheelbarrow", "s7q19": "own_ironfencing", 
                          "s7q20": "own_farmanimals", "s8q1": "relatives_abroad", "s8q2": "relati")}

In [42]:
#Energy Rename
Energy = Energy.rename(columns={"s1q2":"hhlocation", "s12q12a":"q_purchased_firewoodused", 
                       "s12q12b": "totalcost_purchasedfirewood",
                     "s12q13a": "q_collected_firewoodused","s12q13b": "totalcost_collectedfirewood",
                      "s12q14a": "q_farmresidue_used", "s12q14b": 'totalcost_farmresidue',
                      's12q15a':'q_wood/processwaste_used', 's12q15b': 'totalcost_wood/processwaste',
                      's12q16a': 'q_charcoal_used', 's12q16b': 'totalcost_charcoal',
                      's12q17a': 'q_kerosene/paraffin_used', 's12q17b': 'totalcost_kerosene/paraffin',
                      's12q18a': 'q_lpg_used', 's12q18b': 'totalcost_lpg', 
                      's12q19a': 'q_electricity_used', 's12q19b': 'totalcost_electricity',
                      's12q20a': 'q_petrol_used', 's12q20b': 'totalcost_petrol',
                       's12q21a': 'q_diesel_used', 's12q21b': 'totalcost_diesel'})

In [50]:
Energy = Energy.drop(['s12q12', 's12q12a_1', 's12q13', 's12q13a_1', 's12q14', 's12q14a_1',
            's12q15', 's12q15a_1', 's12q16', 's12q16a_1', 's12q17', 's12q18'], axis = 1)

In [21]:
#Education Rename
Education = Education.rename(columns={'s4q10': 'spend_tuitionfees', 's4q11': 'spend_textbooks', 
                         's4q12': 'spend_exercisebooks', 's4q13': 'spend_schooluniform',
                         's4q14': 'spend_schoolboardingfees', 's4q15': 'spend_schooltransport',
                         's4q16': 'spend_extratuition', 's4q17': 'spend_PTA', 
                         's4q18': 'spend_pocketmoney', 's4q19': 'spend_cautionmoney',
                         's4q20': 'spend_educmedicalfee', 's4q21': 'spend_activityfees',
                         's4q22': 'spend_examfees', 's4q23': 'spend_educfeedingprogram',
                         's4q24': 'spend_othereduccharges'})

,hhid,s1q2,spend_tuitionfees,spend_textbooks,spend_exercisebooks,spend_schooluniform,spend_schoolboardingfees,spend_schooltransport,spend_extratuition,spend_PTA,spend_pocketmoney,spend_cautionmoney,spend_educmedicalfee,spend_activityfees,spend_examfees,spend_educfeedingprogram,spend_othereduccharges,hhsize,weight,popweight
0,10,Village 1,0.0,0.000000,2400.000000,0.0,6000.0,3000.0,2000.000061,0.0,2000.000061,1500.0,1399.999969,799.99997,0.0,0.0,0.0,5,5.557168,27.785840
1,11,Village 1,0.0,0.000000,200.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,20.00000,0.0,0.0,0.0,6,5.557168,33.343010
2,12,Village 1,0.0,0.000000,400.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,6,5.557168,33.343010
3,14,Village 1,0.0,0.000000,250.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,14,5.557168,77.800360
4,15,Village 1,7000.0,0.000000,0.000000,0.0,0.0,0.0,2000.000000,0.0,500.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,2,5.557168,11.114340
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1097,5977,Village 3,0.0,600.000008,7560.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,15,5.557168,83.357530
1098,5986,Village 3,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,2,5.557168,11.114340
1099,5992,Village 2,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00000,250.0,0.0,0.0,1,5.557168,5.557168
1100,6002,Village 3,0.0,0.000000,50.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,4,5.557168,22.228670
1101,6004,Village 3,0.0,0.000000,1000.000031,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.00000,0.0,0.0,0.0,12,5.557168,66.686020